language: julia
os:
  - linux
arch:
  - amd64
  - arm64-graviton2
virt: lxd
group: edge
julia:
  - 1.3
  - nightly
jobs:
  allow_failures:
    - julia: nightly
  fast_finish: true
  exclude:
    - os: osx
      arch: x86
    - os: osx
      arch: arm64
    - os: windows
      arch: arm64
    - julia: nightly
      arch: arm64
notifications:
  email: false
after_success: julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(process_folder())'
